tilapp/config/routes.rb
Rails.application.routes.draw do

  get 'serise/index'
  get 'serise/show'
  get '/', to: 'post#index'
  # get 'post_admin/index'
  resources :post do
    get 'toggle_use_yn', on: :member
  end

  resources :serise do
    get 'toggle_use_yn', on: :member
  end



  resources :post_admin do
    get 'toggle_use_yn', on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html




  namespace :admin do
    resources :post do
      get 'toggle_use_yn', on: :member
    end
    resources :serise do
      get 'toggle_use_yn', on: :member
    end
  end
end

tilapp/app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :thumbnail_image, PostThumbnailImageUploader
    self.table_name = "posts"
    # til_id 글 id
    # user_id 작성자id
    # title 제목
    # content 내용
    # thumbnail_image 썸네일 이미지
    # created_at_sub 작성일수기작성
    # use_yn 노출여부
    # created_at 작성일
    # updated_at 수정일
    has_many :serise, dependent: :destroy, foreign_key: "til_id"
end

tilapp/app/models/serise.rb
class Serise < ApplicationRecord
  self.table_name = "series"
  # series_id                 시리즈 고유키
  # til_id                    post id 외래키
  # series_name               시리즈이름
  # description               시리즈 짧은 설명
  # complete_expectation_day  연재 종료 예정일
  # sort_order                순번
  belongs_to :post, foreign_key: "til_id"
end

tilapp/app/controllers/admin/post_controller.rb
class Admin::PostController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
  end

  def edit
  end

  def new
  end

  def update
  end

  def create
  end
end

tilapp/app/controllers/admin/serise_controller.rb
class Admin::SeriseController < ApplicationController
  def index
    @serises = Serise.all
  end

  def show
  end

  def edit
  end

  def new
  end

  def update
  end

  def create
  end
end

tilapp/app/controllers/post_admin_controller.rb
class PostAdminController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @next_post_id = Post.where("til_id > ?", params[:id]).order(til_id: :asc).first&.til_id
    @prev_post_id = Post.where("til_id < ?", params[:id]).order(til_id: :desc).first&.til_id
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end
  def create
    @post = Post.new(post_params)
    @post.created_at = Time.now
    @post.updated_at = Time.now
    @post.save

    return redirect_to post_admin_index_path
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_admin_path(@post), notice: '글이 수정되었습니다' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_use_yn
    @post = Post.find(params[:id])
    # debugger
    if @post.use_yn == 'Y'
      # debugger
      # @post.update(use_yn: "N")
      @post.use_yn='N'
      @post.save
      # debugger
      return redirect_to post_admin_index_path
    else
      @post.update(use_yn: "Y")
      @post.use_yn='Y'
      @post.save
      return redirect_to post_admin_index_path
    end
  end

  private
  def post_params
    params.require(:post).permit(:user_id, :title, :content, :thumbnail_image )
  end
end

tilapp/app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @posts = Post.where(use_yn: 'Y').order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @next_post_id = Post.where("til_id > ?", params[:id]).order(til_id: :asc).first&.til_id
    @prev_post_id = Post.where("til_id < ?", params[:id]).order(til_id: :desc).first&.til_id
  end

  # def new
  #   @post = Post.new
  # end
  #
  # def edit
  #   @post = Post.find(params[:id])
  # end

  # def create
  #   @post = Post.new(post_params)
  #   @post.created_at = Time.now
  #   @post.updated_at = Time.now
  #   @post.save
  #
  #   return redirect_to post_index_path
  # end
  #
  # def update
  #   @post = Post.find(params[:id])
  #
  #   respond_to do |format|
  #     if @post.update(post_params)
  #       format.html { redirect_to post_path(@post), notice: '글이 수정되었습니다' }
  #       format.json { render :show, status: :ok, location: @post }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # def toggle_use_yn
  #     @post = Post.find(params[:id])
  #     # debugger
  #     if @post.use_yn == 'Y'
  #       # debugger
  #       # @post.update(use_yn: "N")
  #       @post.use_yn='N'
  #       @post.save
  #       # debugger
  #       return redirect_to post_index_path
  #     else
  #       @post.update(use_yn: "Y")
  #       @post.use_yn='Y'
  #       @post.save
  #       return redirect_to post_index_path
  #     end
  # end
  #
  # private
  #   def post_params
  #     params.require(:post).permit(:user_id, :title, :content, :thumbnail_image )
  #   end
end

tilapp/app/controllers/serise_controller.rb
class SeriseController < ApplicationController
  def index
    @serises = Serise.all
    @posts = Post.all
  end

  def show
    @serise = Serise.find(params[:id])
  end
end

tilapp/app/helpers/post_admin_helper.rb
module PostAdminHelper
end

tilapp/app/helpers/post_helper.rb
module PostHelper
end

tilapp/app/helpers/serise_helper.rb
module SeriseHelper
end

tilapp/app/views/admin/post/_form.html.erb
<script>

      $(document).ready(function() {
          var note = $('#post_content');
          note.summernote({
              placeholder: '내용을 입력해주세요',
              tabsize: 2,
              height: 450,
              lang: 'ko-KR',
              toolbar: [
              // [groupName, [list of button]]
              ['fontname', ['fontname']],
              ['fontsize', ['fontsize']],
              ['style', ['bold', 'italic', 'underline','strikethrough', 'clear']],
              ['color', ['forecolor','color']],
              ['table', ['table']],
              ['para', ['ul', 'ol', 'paragraph']],
              ['height', ['height']],
              ['insert',['picture','link','video']],
              ['view', ['fullscreen', 'help']]
            ],
            fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New','맑은 고딕','궁서','굴림체','굴림','돋음체','바탕체'],
            fontSizes: ['8','9','10','11','12','14','16','18','20','22','24','28','30','36','50','72']
          });
      });
</script>
<%= form_with model: @post, url: url, locale: true do |f| %>
  <div>
    <%= f.label :user_id, '작성자'%>
    <div><%= f.text_field :user_id %></div>
  </div>
  <div>
    <%= f.label :title, '제목'%>
    <div><%= f.text_field :title %></div>
  </div>
  <div>
    <%= f.label :thumbnail_image, '썸네일이미지' %>
    <div><%= f.file_field :thumbnail_image %></div>
  </div>


  <div>
    <%= f.label :CONT, '내용', class: 'col-sm-2 col-form-label' %>
    <div>
      <textarea name="post[content]" id="post_content" rows="10" class="form-control"><%= @post.content %></textarea>
    </div>
  </div>
  <div>
    <%= f.submit '저장' %>
  </div>

<% end %>
<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

tilapp/app/views/admin/post/edit.html.erb
<h1>Serise#edit</h1>
<p>Find me in app/views/serise/edit.html.erb</p>

tilapp/app/views/admin/post/index.html.erb
<style>
  table, thead, th, tr, td, tbody {
      border: 1px solid black;
  }
</style>

<h1>Serise#index</h1>
<p>Find me in app/views/serise/index.html.erb</p>

<section class="title">
  글목록
</section>
<article>
  <table class="table table-hover table-bordered data-tables">
    <thead>
    <tr>
      <% %w(id 작성일 제목 시리즈id 관리 삭제 ).each do |column| %>
        <th><span class="nowrap"><%= column %></span></th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @posts.each do |t| %>
      <tr>
        <td><%= t.til_id %></td>
        <td><%= t.created_at %></td>
        <td><%= t.title %></td>
        <td></td>
        <td>관리</td>
        <td>삭제</td>


      </tr>
    <% end %>
    </tbody>
  </table>
</article>
<script>
    $(document).ready(function() {
        $('.data-tables').DataTable({
            "pageLength": 50,
            "order": []
        });
    })
</script>

tilapp/app/views/admin/post/new.html.erb
<h1>Serise#new</h1>
<p>Find me in app/views/serise/new.html.erb</p>

tilapp/app/views/admin/post/show.html.erb
<h1>Serise#show</h1>
<p>Find me in app/views/serise/show.html.erb</p>

tilapp/app/views/admin/serise/_form.html.erb
<script>

      $(document).ready(function() {
          var note = $('#post_content');
          note.summernote({
              placeholder: '내용을 입력해주세요',
              tabsize: 2,
              height: 450,
              lang: 'ko-KR',
              toolbar: [
              // [groupName, [list of button]]
              ['fontname', ['fontname']],
              ['fontsize', ['fontsize']],
              ['style', ['bold', 'italic', 'underline','strikethrough', 'clear']],
              ['color', ['forecolor','color']],
              ['table', ['table']],
              ['para', ['ul', 'ol', 'paragraph']],
              ['height', ['height']],
              ['insert',['picture','link','video']],
              ['view', ['fullscreen', 'help']]
            ],
            fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New','맑은 고딕','궁서','굴림체','굴림','돋음체','바탕체'],
            fontSizes: ['8','9','10','11','12','14','16','18','20','22','24','28','30','36','50','72']
          });
      });
</script>
<%= form_with model: @post, url: url, locale: true do |f| %>
  <div>
    <%= f.label :user_id, '작성자'%>
    <div><%= f.text_field :user_id %></div>
  </div>
  <div>
    <%= f.label :title, '제목'%>
    <div><%= f.text_field :title %></div>
  </div>
  <div>
    <%= f.label :thumbnail_image, '썸네일이미지' %>
    <div><%= f.file_field :thumbnail_image %></div>
  </div>


  <div>
    <%= f.label :CONT, '내용', class: 'col-sm-2 col-form-label' %>
    <div>
      <textarea name="post[content]" id="post_content" rows="10" class="form-control"><%= @post.content %></textarea>
    </div>
  </div>
  <div>
    <%= f.submit '저장' %>
  </div>

<% end %>
<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

tilapp/app/views/admin/serise/edit.html.erb
<h1>Serise#edit</h1>
<p>Find me in app/views/serise/edit.html.erb</p>

tilapp/app/views/admin/serise/index.html.erb
<h1>Serise#index</h1>
<p>Find me in app/views/serise/index.html.erb</p>

<% @serises.each do |t| %>
  <%= t.series_id %>
<% end %>

tilapp/app/views/admin/serise/new.html.erb
<h1>Serise#new</h1>
<p>Find me in app/views/serise/new.html.erb</p>

tilapp/app/views/admin/serise/show.html.erb
<h1>Serise#show</h1>
<p>Find me in app/views/serise/show.html.erb</p>

tilapp/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>kind-til</title>
  <!-- include libraries(jQuery, bootstrap) -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Datatables CSS -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" >
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body>
<%= yield %>
<footer>
  <ul>
    <li>admin</li>
    <li>2020.10.01</li>
    <li>Rails 6.0.3.3</li>
    <li>ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]</li>
    <li>sqlite3</li>
    <li>Docker version 18.09.8, build bfed4f5</li>
    <li>01049055202</li>
  </ul>
</footer>

<!-- Datatables CDN -->
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

</body>
</html>

tilapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>kind-til</title>
    <!-- include libraries(jQuery, bootstrap) -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Datatables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" >
    <link rel="stylesheet" href="/admin/admin.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>
  <body>
    <%= yield %>
    <footer>
      <ul>
        <li>2020.10.01</li>
        <li>Rails 6.0.3.3</li>
        <li>ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]</li>
        <li>sqlite3</li>
        <li>Docker version 18.09.8, build bfed4f5</li>
        <li>01049055202</li>
      </ul>
    </footer>

    <!-- Datatables CDN -->
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

  </body>
</html>

tilapp/app/views/post/edit.html.erb
<style>
    .btn{
        border: 1px solid chocolate;
        margin: 10px 5px;
    }
    header {
        border: 1px solid saddlebrown ;
        border-radius: 5px;
        margin: 10px 5px;
        padding: 10px 5px;
    }
    form {
        border: 1px solid saddlebrown ;
        border-radius: 5px;
        margin: 10px 5px;
        padding: 10px 5px;
    }
    li {
        list-style: none;
    }
    footer {
        border: 1px solid saddlebrown ;
        border-radius: 5px;
        margin: 10px 5px;
        padding: 10px 5px;
    }
</style>

<%= link_to "Back", :back , class: "btn" %>
<header>수정하기</header>
<%= render 'form', url: post_path %>

tilapp/app/views/post/index.html.erb
<head>

  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-176390406-2', 'auto');
      ga('send', 'pageview'); // pageview 전용

  </script>

  <style>
    a:link {text-decoration: none; color: midnightblue;}
    a:visited {text-decoration: none; color: midnightblue;}
    a:active {text-decoration: none; color: midnightblue;}
    a:hover {text-decoration: none; color: midnightblue;}

    header{
        font-size: 50px;
        margin: 10px 5px;
        padding: 10px 5px;
        border: 1px solid #730E15;
    }

    section {
        border: 1px solid black;
        border-radius: 10px;
    }

    .section_title {
        margin: 10px 5px;
        padding: 50px 5px;
        font-size: 40px;
    }

    .section_title img{
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }

    article{
        border: 1px solid saddlebrown ;
        border-radius: 10px;
        margin: 10px 5px;
        padding: 10px 5px;
    }

    .thum_image img {
        width: 100%;
    }


    .btn{
        border: 1px solid chocolate;
        padding: 2px;
    }

    .article_controler{
        /*border: 1px solid palevioletred;*/
        margin: 5px 0 5px 0;
    }

    li {
        list-style: none;
    }

    footer {
        border: 1px solid saddlebrown ;
        border-radius: 5px;
        margin: 10px 5px;
        padding: 10px 5px;
    }
  </style>

</head>
<body>
    <header>
      🐜 개미개발일지
    </header>
    <section class="section_title">
      <p>가장 호사스러운 웹 호스팅 ( 시놀로지 나스와 docker 를 이용한 홈 웹 호스팅 )</p>
      <h4>카테고리 생성일 2020.10.04 </h4>
    </section>
    <% @posts.each do |post| %>
    <article>
      <div class="article_controler">
      </div>
      <div class="thum_image"><img src="<%= post&.thumbnail_image %>" alt=""> </div>
      <div> <%= post.title %> </div>
      <div> 생성일 <%= post.created_at&.strftime('%Y-%m-%d') %> </div>
      <div> <%= link_to '상세보기', post_path(post), class: 'btn' %></div>
    </article>
    <% end %>
</body>

tilapp/app/views/post/new.html.erb
<%= link_to "뒤로", :back , class: 'btn'%>
<h1>새글작성</h1>
<%= render 'form', url: post_index_path%>

tilapp/app/views/post/show.html.erb
<head>
<style>
      a:link {text-decoration: none; color: midnightblue;}
      a:visited {text-decoration: none; color: midnightblue;}
      a:active {text-decoration: none; color: midnightblue;}
      a:hover {text-decoration: none; color: midnightblue;}

      header{
          margin: 10px 5px;
          padding: 10px 5px;
          border: 1px solid #730E15;
          padding: 10px;
      }

      section {
          margin: 10px 5px;
          padding: 10px 5px;
          border: 1px solid black;
          border-radius: 10px;
      }

      .section_title {
          font-size: 40px;
      }


      article{
          border: 1px solid saddlebrown ;
          border-radius: 10px;
          margin: 10px 5px;
          padding: 10px 5px;
      }

      .thum_image img {
        width: 100%;
      }

      .btn{
          border: 1px solid chocolate;
          padding: 2px;
      }

      .article_controler{
          /*border: 1px solid palevioletred;*/
          margin: 5px 0 5px 0;
      }

      li {
          list-style: none;
      }

      footer {
          border: 1px solid saddlebrown ;
          border-radius: 5px;
          margin: 10px 5px;
          padding: 10px 5px;
      }

      .colorscripter-code {
        display: grid;
      }
  </style>


</head>
  <%= link_to "Back", :back %>
  <%= link_to '목록보기', post_index_path %>
  <header>
    상세보기
  </header>
  <section>
    <div class="thum_image">
      <img src="<%= @post&.thumbnail_image %>" alt=""></div>
    </div>
  </section>
  <section>
    <%= @post.title %>
  </section>
  <article>
    <div><%= @post.til_id %></div>
    <div><%= @post.created_at.strftime('%Y-%m-%d') %></div>
    <div>작성자: <%= @post.user_id %></div>

    <div><%= @post.content.html_safe %></div>
  </article>
  <section>
    <span>
      <% if @prev_post_id.present?  %>
        <%= link_to '이전글', post_path(@prev_post_id) %>
      <% end %>
    </span>
      <span>
      <% if @next_post_id.present?  %>
        <%= link_to '다음글', post_path(@next_post_id) %>
      <% end %>
    </span>
  </section>

tilapp/app/views/post_admin/_form.html.erb
<script>

      $(document).ready(function() {
          var note = $('#post_content');
          note.summernote({
              placeholder: '내용을 입력해주세요',
              tabsize: 2,
              height: 450,
              lang: 'ko-KR',
              toolbar: [
              // [groupName, [list of button]]
              ['fontname', ['fontname']],
              ['fontsize', ['fontsize']],
              ['style', ['bold', 'italic', 'underline','strikethrough', 'clear']],
              ['color', ['forecolor','color']],
              ['table', ['table']],
              ['para', ['ul', 'ol', 'paragraph']],
              ['height', ['height']],
              ['insert',['picture','link','video']],
              ['view', ['fullscreen', 'help']]
            ],
            fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New','맑은 고딕','궁서','굴림체','굴림','돋음체','바탕체'],
            fontSizes: ['8','9','10','11','12','14','16','18','20','22','24','28','30','36','50','72']
          });
      });
</script>
<%= form_with model: @post, url: url, locale: true do |f| %>
  <div>
    <%= f.label :user_id, '작성자'%>
    <div><%= f.text_field :user_id %></div>
  </div>
  <div>
    <%= f.label :title, '제목'%>
    <div><%= f.text_field :title %></div>
  </div>
  <div>
    <%= f.label :thumbnail_image, '썸네일이미지' %>
    <div><%= f.file_field :thumbnail_image %></div>
  </div>


  <div>
    <%= f.label :CONT, '내용', class: 'col-sm-2 col-form-label' %>
    <div>
      <textarea name="post[content]" id="post_content" rows="10" class="form-control"><%= @post&.content %></textarea>
    </div>
  </div>
  <div>
    <%= f.submit '저장' %>
  </div>

<% end %>
<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

tilapp/app/views/post_admin/index.html.erb
<head>

  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-176390406-2', 'auto');
      ga('send', 'pageview'); // pageview 전용

  </script>

  <style>
      a:link {text-decoration: none; color: midnightblue;}
      a:visited {text-decoration: none; color: midnightblue;}
      a:active {text-decoration: none; color: midnightblue;}
      a:hover {text-decoration: none; color: midnightblue;}

      header{
          margin: 10px 5px;
          padding: 10px 5px;
          border: 1px solid #730E15;
          padding: 10px;
      }

      section {
          margin: 10px 5px;
          padding: 10px 5px;
          border: 1px solid black;
          border-radius: 10px;
      }

      .section_title {
          font-size: 40px;
      }


      article{
          border: 1px solid saddlebrown ;
          border-radius: 10px;
          margin: 10px 5px;
          padding: 10px 5px;
      }

      .thum_image img {
        width: 100%;
      }

      .btn{
          border: 1px solid chocolate;
          padding: 2px;
      }

      .article_controler{
          /*border: 1px solid palevioletred;*/
          margin: 5px 0 5px 0;
      }

      li {
          list-style: none;
      }

      footer {
          border: 1px solid saddlebrown ;
          border-radius: 5px;
          margin: 10px 5px;
          padding: 10px 5px;
      }
  </style>

</head>
<body>
<header>
  <span><%= link_to '새글작성', new_post_admin_path %></span>
</header>


<section>
  <span class="section_title">nas는 사랑입니다</span>
</section>
<% @posts.each do |post| %>
  <article>
    <div class="article_controler">
      <% if post.use_yn == 'Y' %>
        <%= link_to "미노출", toggle_use_yn_post_admin_path(post), class: 'btn' %>
      <% else %>
        <%= link_to "노출", toggle_use_yn_post_admin_path(post), class: 'btn' %>
      <% end %>

      <%= link_to '상세보기', post_admin_path(post), class: 'btn' %>
      <%= link_to '수정하기', edit_post_admin_path(post), class: 'btn'  %>
    </div>
    <div class="thum_image"><img src="<%= post&.thumbnail_image %>" alt=""> </div>
    <div> <%= post.title %> </div>
    
    <div> 생성일 <%= post.created_at&.strftime('%Y-%m-%d') %> </div>
  </article>
<% end %>
</body>

tilapp/app/views/serise/index.html.erb
<h1>Serise#index</h1>
<p>Find me in app/views/serise/index.html.erb</p>
<section class="title"">
  시리즈 목록
</section class>

<% @serises.each do |t| %>
  <article>

    <div><%= t.series_id %></div>

    <%= link_to serise_path(t) do %>
      <div><%= t.series_name %></div>
    <% end %>

    <div><%= t.series_name %></div>
    <div><%= t.description %></div>
    <div><%= t.complete_expectation_day %></div>
    <div><%= t.sort_order %></div>
    <div><%= t.created_at %></div>
  </article>
<% end %>

<section class="title">
  글 목록
</section>
<% @posts.each do |t| %>
    <article>

      <div><%= t.til_id %></div>
      <div><%= t.user_id %></div>
      <div><%= t.title %></div>
      <div><%= t.content %></div>
      <div><%= t.thumbnail_image %></div>
      <div><%= t.created_at %></div>
      <div><%= t.til_id %></div>
      <div><%= t.til_id %></div>


    </article>
<% end %>

tilapp/app/views/serise/show.html.erb
<header>
  <%= link_to '뒤로가기', :back %>
  <%= link_to '메인', serise_index_path %>
</header>

<h1>Serise#show</h1>
<p>Find me in app/views/serise/show.html.erb</p>

<section class="title">
  <%= @serise.series_name %>
</section>
<article>
  <div><%= @serise.series_name %></div>
  <div><%= @serise.description %></div>
  <div><%= @serise.complete_expectation_day %></div>
  <div><%= @serise.sort_order %></div>
  <div><%= @serise.created_at %></div>
</article>